name: 💡 Suggestion or enhancement
description: Suggest a new feature or enhancement for the FastPluginConfigurer
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of what the suggestion is.
      placeholder: I'd like it if the FastPluginConfigurer would let you do...
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Extra details
      description: Please provide any other information in the space below.
    validations:
      required: false
